### ISSUE TITLE
App Center Discover starts but closes itself after 1 second

### ISSUE THREAD

**Issue by Ubuntu-2020** [OpenMandrivaAssociation/distribution#2896] opened 2023-04-17 11:46 UTC
**OpenMandriva version**:
openmandriva.rome-23.03-plasma.x86_64

**Describe the bug**:
App Center Discover starts but closes itself after 1 second

**Steps to reproduce**:
Launching App Center Discover.
It closes itself after 1 second.

**Observed behavior**:

**Expected behavior**:

**Additional comment**:
The operating system is installed in Russian language.

**Logs and screenshots if relevant**
Please tell me the code for the terminal so that I can post the error code if it appears in the terminal.

**Comment by benbullard79** [comment] 2023-04-17 17:39
My system is installed in English language. Discover opens here and stays open. So the trouble shooting steps are the same as I posted recently in [https://github.com/OpenMandrivaAssociation/distribution/issues/2869](url).

1. Attach the omv-bug-report.log

![Screenshot_20230417_111231](https://user-images.githubusercontent.com/5704386/232546594-8526a9b0-a7f9-4379-87f3-e8ca391635d0.jpg)

2. Note the time and launch Discover from terminal and post the output here.

3. After launching Discover check journal log to see if there is anything relevant there. Open Konsole and type `journalctl -b`. Look for the time you noted above and see if you see anything that may be relevant. 

4. You can post the journal log by running `journalctl -b > journal.txt` and then post the file journal.txt here. In general it is a good idea to post the entire output of things not the parts user thinks may be relevant. One never knows what devs may find to be most important.

5. For non-English computers to make output easier to read for folks trying to help use this `LC_ALL=C`. Example: `sudo LC_ALL=C journalctl` or. Using a translator on terminal output or code is not very workable.

**Comment by benbullard79** [comment] 2023-04-17 17:46
> **Logs and screenshots if relevant** Please tell me the code for the terminal so that I can post the error code if it appears in the terminal.

`$ LC_ALL=C plasma-discover`

Here that looks like this:

```
$ LC_ALL=C plasma-discover
adding empty sources model QStandardItemModel(0x56457a2790a0)
QObject::startTimer: Timers cannot have negative intervals
packagekitqt.transaction: Unknown Transaction property: "Sender" QVariant(QString, ":1.294")
file:///usr/lib64/qt5/qml/org/kde/kirigami.2/ScrollablePage.qml:200:9: QML MouseArea: Binding loop detected for property "implicitHeight"
file:///usr/lib64/qt5/qml/org/kde/kirigami.2/ScrollablePage.qml:200:9: QML MouseArea: Binding loop detected for property "implicitHeight"
file:///usr/lib64/qt5/qml/org/kde/kirigami.2/ScrollablePage.qml:200:9: QML MouseArea: Binding loop detected for property "implicitHeight"
file:///usr/lib64/qt5/qml/org/kde/kirigami.2/ScrollablePage.qml:200:9: QML MouseArea: Binding loop detected for property "implicitHeight"
file:///usr/lib64/qt5/qml/org/kde/kirigami.2/ScrollablePage.qml:200:9: QML MouseArea: Binding loop detected for property "implicitHeight"
packagekitqt.transaction: Unknown Transaction property: "Sender" QVariant(QString, ":1.294")
packagekitqt.transaction: Unknown Transaction property: "Sender" QVariant(QString, ":1.294")
```

Since your Discover is crashing you should see something different like a core dump or segfault.

**Comment by Ubuntu-2020** [comment] 2023-04-18 11:02
I attach photos.
The program window appears for one second:
![plasma-Discover-run](https://user-images.githubusercontent.com/65112331/232757616-dda86a06-fcea-4532-9ffc-de4d654847ed.png)

After a second, the program closes and an error message appears:
![plasma-Discover-failed](https://user-images.githubusercontent.com/65112331/232757646-8b6c5220-08fb-41ec-b1cd-ba8cdfd5a220.png)

**Comment by rugyada** [comment] 2023-04-18 12:01
> As a result, I get a huge response from the terminal:
> [...]

@Ubuntu-2020 Learn:
_For non-English computers to make output easier to read for folks trying to help use this_ `LC_ALL=C`

**Comment by benbullard79** [comment] 2023-04-19 13:25
The `LC_ALL=C plasma-discover` output is a lot of lines but it shows same problem repeated many times:

`KNS error`
`invalid kns backend!`

I asked about this on [OpenMandriva Chat](https://wiki.openmandriva.org/en/team/chat). You are welcome there also if you wish to talk directly to developers.

Got this response from a developer on OpenMandriva Chat: "I don't see why that would fail (except on a box that isn't connected to the internet), https://autoconfig.kde.org/ocs/providers.xml loads fine here and does list the KNS providers".

I checked that myself and https://autoconfig.kde.org/ does connect and lists the KNS providers. So perhaps something involving your internet connection? Try changing DNS?

Also try deleting this file `/home/user_name/.cache/discover`. Where you replace `user_name` with your actual user name.

**Comment by benbullard79** [comment] 2023-04-19 14:04
One more thing someone noticed in Chat: 

"maybe that fonts issue?
KNS error in "Fonts" : KNSCore::ProviderError "Loading of providers from file: https://cdn.kde.org/khotnewstuff/v1/fonts-providers.xml failed" QVaria
nt(QString, "https://cdn.kde.org/khotnewstuff/v1/fonts-providers.xml")
invalid kns backend! "/usr/share/knsrcfiles/kfontinst.knsrc" because: "Invalid Fonts backend, contact your distributor.""

I checked and here https://cdn.kde.org/khotnewstuff/v1/ does not seem to work. https://cdn.kde.org/khotnewstuff/v2 does work. But I have no idea why your Discover would pull that URL where mine does not give any such error.

These are the discover packages I have:

```
$ rpm -qa | grep discover
lib64hpdiscovery0-3.22.10-1.znver1
discover-backend-flatpak-5.27.3-1.znver1
discover-backend-fwupd-5.27.3-1.znver1
discover-backend-kns-5.27.3-1.znver1
discover-backend-packagekit-5.27.3-1.znver1
discover-5.27.3-1.znver1
```

If you have a x86_64 system yours would say that instead of znver1.

**Comment by Ubuntu-2020** [comment] 2023-04-22 11:33
> Also try deleting this file `/home/user_name/.cache/discover`. Where you replace `user_name` with your actual user name.

I delete hidden folder **.cache/discover**.
Launched discover but after a second it closed anyway.

> **Edit:** Another suggestion from folks at OpenMandriva Chat, run this to eliminate more of the Discover cache:
> `sudo rm -rf /var/cache/PackageKit/* /var/cache/app-info/*`

In theory, these commands should have removed something.
But for these commands in the terminal, nothing appeared and was not deleted.
As a result, a message appeared impossible to delete **'/var/cache/PackageKit/*'**: No such file or directory.

> **Edit:** Also try logging it as another user with no customization and see if that affects anything.

Created another user.
Booted with Plasma desktop.
Launched Discover and it closed in a second.

These are the discover packages I have:
```
$ rpm -qa | grep discover 
lib64hpdiscovery0-3.22.10-1.x86_64 
discover-backend-fwupd-5.27.3-1.x86_64 
discover-backend-kns-5.27.3-1.x86_64 
discover-backend-packagekit-5.27.3-1.x86_64 
discover-5.27.3-1.x86_64 
discover-backend-flatpak-5.27.3-1.x86_64
```

P.S.: I should note that in addition to installing the system in Russian, I downloaded the external views as in **Windows 10**, **Windows 7**, **macOS** and so on from the **Desktop Presets**:
 ![om-feelike](https://wiki.openmandriva.org/images/om4.2-feelike-003.jpg)

**Comment by rugyada** [comment] 2023-06-02 12:43
Closing as the bug has not been confirmed. Feel free to reopen if the case and provide further info.

**Closed by rugyada** 2023-06-02 12:43 UTC
Labels: ROME/rolling
