### ISSUE TITLE
Installation with BTRFS or XFS root failed at grub2-install

### ISSUE THREAD

**Issue by NO-MEANINGS** [OpenMandrivaAssociation/distribution#2777] opened 2022-02-23 09:27 UTC
**OpenMandriva version**:
4.3

**Describe the bug**:
Installation with btrfs root will fail at grub2-install

**Steps to reproduce**:
1. Boot OMA live image, open the installer. (Use generic X86_64 image, not sure if znver1 image can reproduce this)
2. In the partitioning step, chose manual, create a btrfs file system mounted at / 
3. Continue installation process as normal

**Observed behavior**:
Installer failed while executing grub2-install
For a screenshot:
https://forum.openmandriva.org/uploads/default/original/2X/5/5232750ef0c49f8fee8ab875151c6b14e4e0c7de.png

**Expected behavior**:
The installation should success

**Logs and screenshots if relevant**
There is a related forum thread
https://forum.openmandriva.org/t/installation-with-root-btrfs-failed-at-grub2-install/4400

For full calamares log:
https://bin.disroot.org/?556fe53156d11b97#DbXuD11DDG3ZaK1aKrPphgE2EXTk2N7HYU2ugBhuKa8y

**Comment by tpgxyz** [comment] 2022-02-24 09:23
Hi, thanks for sharing your issue with us.
According to your logs, grub2-install fails to install because /boot/efi is missing, which is not true.
```
6:45:32 [6]: static CalamaresUtils::ProcessResult CalamaresUtils::System::runCommand(System::RunLocation, const QStringList &, const QString &, const QString &, std::chrono::seconds)
    Running "env" ("mount", "-t", "vfat", "/dev/nvme0n1p1", "/tmp/calamares-root-wuz79ewo/boot/efi") 
    ..  Finished. Exit code: 0 
```
```
[PYTHON JOB]:  "Bootloader: grub (efi)" 
16:46:31 [6]: static CalamaresUtils::ProcessResult CalamaresUtils::System::runCommand(System::RunLocation, const QStringList &, const QString &, const QString &, std::chrono::seconds)
    Running "chroot" ("/tmp/calamares-root-wuz79ewo", "grub2-install", "--target=x86_64-efi", "--efi-directory=/boot/efi", "--bootloader-id=OpenMandriva_Lx_[GRUB]", "--force") 
    ..  Target cmd: ("grub2-install", "--target=x86_64-efi", "--efi-directory=/boot/efi", "--bootloader-id=OpenMandriva_Lx_[GRUB]", "--force") Exit code: 1 output:
 Installing for x86_64-efi platform.
grub2-install: error: cannot find a device for /boot/grub2 (is /dev mounted?).
```

**Comment by benbullard79** [comment] 2022-03-02 22:06
I tried an install with Rolling ISO # 623 on hardware and got same error. 
![Screenshot_20220302_155204](https://user-images.githubusercontent.com/5704386/156457536-5b7a035f-83a2-469a-86a7-5f94d68410b6.jpg)

[calamares.log.txt](https://github.com/OpenMandrivaAssociation/distribution/files/8173238/calamares.log.txt)

**Comment by omakuta** [comment] 2022-04-07 03:53
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/btrfs-filesystem/4340/7

**Comment by benbullard79** [comment] 2022-06-04 15:54
Sad to report a regression in this problem. Now it seems we can not install to XFS either.

Attaching log of attempt to install from Cooker iso #938 using XFS.

[cala-xfx-fail.txt](https://github.com/OpenMandrivaAssociation/distribution/files/8838200/cala-xfx-fail.txt)

**Comment by benbullard79** [comment] 2022-07-16 09:07
This problem appears to be fixed with both btrfs and xfs in Cooker. We are working on some other changes that need to finish so we can make Cooker isos and test this.

So the fix if successful would next show up in next major Rolling upgrade and next version of Rock.

I do not want to close this until I see testing that does not require any user workaround using our isos. Hope this happens soon.

**Comment by benbullard79** [comment] 2022-07-27 17:27
Fix will appear in next iteration of Rolling and next release of Rock.

**Closed by benbullard79** 2022-07-27 17:27 UTC
Labels: bug, 4.3, in progress, rolling, new
