### ISSUE TITLE
Removing entries from favorites section in Application Launcher fails in ROME (X86_64) KDE Plasma edition

### ISSUE THREAD

**Issue by hakerdefo** [OpenMandrivaAssociation/distribution#2887] opened 2023-04-02 17:42 UTC
Removal of `Favorites` entries in KDE Plasma's `Application Launcher` is not immediately possible. Changing `Application Launcher` to `Application Menu` and `Application Dash` doesn't make any difference. Entries from `Favorites` section don't go away by clicking-on `Remove from Favorites` via the context-menu (Right click menu). If system is rebooted, then in some cases, these entries get removed and sometimes, they don't. A system reboot isn't and shouldn't be necessary for this.

**Comment by rugyada** [comment] 2023-04-02 18:12
[OpenMandriva wiki](https://wiki.openmandriva.org/en/distribution/releases/rome/errata#addremove-favorites-to-application-launcher)

**Comment by hakerdefo** [comment] 2023-04-02 18:15
Thanks ruru but don't you think it shouldn't be that difficult? Anyways, I'm glad that the dev team is aware of this bug and hopefully it'll get resolved soon.

**Comment by rugyada** [comment] 2023-04-02 18:29
Yes devs are aware since longtime.
Frankly this is one of the most trivial still annoying bug I ever encountered.  I myself tried to get it sorted a gazillion times without any luck.
Not even people at KDE bugzilla have been able to help.

**Comment by hakerdefo** [comment] 2023-04-02 18:35
I know a couple of people who are good at plasma and see what comes out of it :crossed_fingers: 

Thanks again for the detailed info. BTW the Slim edition of the latest ROME is really really good. Kudos to you guys :+1:

**Comment by rugyada** [comment] 2023-04-02 18:40
> I know a couple of people who are good at plasma and see what comes out of it

Thanks, please do if you can.



> the Slim edition of the latest ROME is really really good. Kudos to you guys

;-)
Thank you.

Aside, [this is my bug report](https://github.com/OpenMandrivaAssociation/distribution/issues/2844).
I have been told "_The issue should get fixed with upcoming Plasma6_"
Fingers crossed.

**Comment by hakerdefo** [comment] 2023-04-02 18:44
Yes, hopefully it will :crossed_fingers:

**Comment by benbullard79** [comment] 2023-04-02 20:36
Thanks for reporting [hakerdefo](https://github.com/hakerdefo). This bug report is a duplicate of [this one]([hakerdefo](https://github.com/hakerdefo)).

**Closed** 2024-07-07 07:58 UTC
Labels: help wanted, cooker, ROME/rolling
