### ISSUE TITLE
Internet graphics not working in System Monitor

### ISSUE THREAD

**Issue by Ubuntu-2020** [OpenMandrivaAssociation/distribution#2869] opened 2023-01-12 08:58 UTC
**OpenMandriva version**: 4.3

**Describe the bug**:
Internet graphics not working in System Monitor

**Steps to reproduce**:
We connect to the Internet and launch a web browser and System Monitor.
We see that we are on the Internet, but nothing is displayed in the System Monitor.
There is no speed graph or information about how much is downloaded and given to the Internet.

**Observed behavior**:

**Expected behavior**:

**Additional comment**:
I'm sorry for not quite in the right topic leaving a comment.
If you know where it should be moved, then move this topic to the correct topic.

**Logs and screenshots if relevant**
![Network-in-OpenMandriva-4-3](https://user-images.githubusercontent.com/65112331/212022242-769b9568-9505-49fa-a480-85c4e247f476.png)

**Comment by benbullard79** [comment] 2023-01-12 16:26
You mean like this:

![Screenshot_20230112_102410](https://user-images.githubusercontent.com/5704386/212123906-c07283c2-cd9c-4773-bc59-cab21ce727e8.jpg)

Works for me.

**Comment by Ubuntu-2020** [comment] 2023-01-13 13:11
@benbullard79
In **OpenMandriva 4.1** it was the same situation. The Internet graphics are not working in System Monitor.
I see your screenshot and I have a request.
Add a count of downloaded and uploaded traffic as in **Ubuntu System Monitor** (_Total Received_ and _Total Sent_):
![system-monitor-ubuntu-2011](https://user-images.githubusercontent.com/65112331/212326517-7bfa1e63-d932-4358-915d-58f91363b7ef.jpg)

**Comment by benbullard79** [comment] 2023-01-28 00:26
> Add a count of downloaded and uploaded traffic as in **Ubuntu System Monitor** (_Total Received_ and _Total Sent_):

You are trying to compare KDE System Monitor with Ubuntu System Monitor. They are not the same are they? I have no idea what desktop Ubuntu is using these days it used to be Gnome. So I can guess that is Gnome System Monitor.

However to me the KDE System Monitor in OMLx does not look right regarding how it reports network stuff, looks like something might be missing. I could be wrong about that and gave up looking on the 'net about this. 

I have no idea how to "Add a count of downloaded and uploaded traffic" to it.

**Comment by berolinux** [comment] 2023-01-28 01:18
This works exactly as it should here with cooker...

![sysmon1](https://user-images.githubusercontent.com/778765/215233743-19140246-8d66-49bd-8d47-80cc45179bc4.png)
![sysmon2](https://user-images.githubusercontent.com/778765/215233754-116d6d94-0340-4f60-aa91-1d48f7c60342.png)

**Comment by benbullard79** [comment] 2023-01-28 01:39
> This works exactly as it should here with cooker...

Good to know. From what I see here it works the same in ROME and Rock/4.3 as it does in Cooker.

**Comment by rugyada** [comment] 2023-01-28 10:05
> Add a count of downloaded and uploaded traffic as in **Ubuntu System Monitor** (_Total Received_ and _Total Sent_):

Maybe Stacer does what you are looking for?

![om-stacer-20230128_105454](https://user-images.githubusercontent.com/46781309/215260383-50326651-082a-4fc5-a9b0-0dbbd9768325.jpg)

![om-stacer-20230128_105936](https://user-images.githubusercontent.com/46781309/215260397-5b29e731-b20e-4948-91ee-17529e01ab9b.jpg)

**Comment by AngryPenguinPL** [comment] 2023-01-28 15:08
gnome-system-monitor works fine too
![Screenshot_20230128_160724](https://user-images.githubusercontent.com/3121142/215273897-e6a2731f-6f98-49e6-9d2d-d39f5906ccf6.png)

**Comment by benbullard79** [comment] 2023-02-13 20:41
Let us close this one. I believe we have determined beyond any reasonable doubt that this issue is not valid. It is expecting something in KDE Plasma software to look like something in Gnome software which is not a reasonable expectation.

**Comment by Ubuntu-2020** [comment] 2023-04-17 11:36
Sorry but in openmandriva.rome-23.03-plasma.x86_64.iso I have the same problem. The Internet graphics are not working in System Monitor.

**Comment by rugyada** [comment] 2023-04-17 12:26
ROME 23.03
It's working as expected here

![ss_20230417_142112](https://user-images.githubusercontent.com/46781309/232483429-350f2827-0bda-42ed-888c-5f7f30b4ba20.jpg)

![ss_20230417_142337](https://user-images.githubusercontent.com/46781309/232483497-42f08521-9aa2-453e-b35c-6deab03829e7.jpg)

**Comment by benbullard79** [comment] 2023-04-17 16:20
> Sorry but in openmandriva.rome-23.03-plasma.x86_64.iso I have the same problem. The Internet graphics are not working in System Monitor.

What exactly is not working? Is it still showing as the screenshot in your first post? Be assured we do want to get this fixed for you. If 3 other people show that the same thing is working then we suspect the problem is not with System Monitor but something specific to users system. To trouble shoot this issue:

Note: The fact you have the same issue in 4.3 and 23.03 is good information. That likely rules out corrupted .iso download or corrupted installation.

1. Attach the omv-bug-report.log

![Screenshot_20230417_111231](https://user-images.githubusercontent.com/5704386/232546594-8526a9b0-a7f9-4379-87f3-e8ca391635d0.jpg)

2. Note the time and launch System Monitor from terminal and post the output if relevant.

3. After launching System Monitor check journal log to see if there is anything relevant there. Open Konsole and type `journalctl -b`. Look for the time you noted above and see if you see anything that may be relevant. 

4. You can post the journal log by running `journalctl -b > journal.txt` and then post the file journal.txt here. In general it is a good idea to post the entire output of things not the parts user thinks may be relevant. One never knows what devs may find to be most important.

Apologies if my earlier response was not adequate.

**Comment by Ubuntu-2020** [comment] 2023-04-18 11:22
It's strange, but today, to my surprise, graphs appeared in the System Monitor:
![OM-Internet](https://user-images.githubusercontent.com/65112331/232761859-23f19147-48a2-4ceb-aa3e-b23adc69df28.png)

**Comment by rugyada** [comment] 2023-04-18 12:09
Glad that you got it now.

**Comment by rugyada** [comment] 2023-04-18 12:12
Looks like it's confirmed not a bug.

**Closed by rugyada** 2023-04-18 12:12 UTC
Labels: invalid, 4.3, ROME/rolling
