### ISSUE TITLE
Display brightness does not change.

### ISSUE THREAD

**Issue by 38github** [OpenMandrivaAssociation/distribution#2812] opened 2022-07-27 17:36 UTC
**OpenMandriva version**: OpenMandriva Lx 4.90

**Describe the bug**: Laptop brightness adjustment does nothing. This has been reported years ago by me. OpenMandriva is the only distribution that has this issue in my experience. 

**Steps to reproduce**: Try to change brightness.

**Observed behavior**: The brightness does not change.

**Expected behavior**: Brightness change

**Additional comment**:

**Logs and screenshots if relevant**:
OpenMandriva Lx 4.90
KDE Plasma Version: 5.25.3
KDE Frameworks Version: 5.96.0
Qt Version: 5.15.5
Kernel Version: 5.18.12-desktop-3omv4090 (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i3-7100U CPU @ 2.40GHz
Graphics Processor: Mesa Intel® HD Graphics 620
Manufacturer: LENOVO
Product Name: 80XK
System Version: Lenovo ideapad 320-14IKB

**Comment by AngryPenguinPL** [comment] 2022-07-27 18:39
Thanks for report. To understand what is worng here can you try edit entry in ` /etc/default/grub`

By default we use somethings like this:
`acpi_osi=Linux acpi_osi='!Windows 2012' acpi_backlight=vendor`

and acpi_backlight is set to `vendor`.

Can you try change it to `native`
and then save file and run in terminal as root command: `update-grub2`

**Comment by bogdro** [comment] 2022-08-04 18:20
You can additionally take a look if this case is similar to yours: https://bugs.kde.org/show_bug.cgi?id=399646.
It was supposed to be fixed in 5.25, so if you find it isn't fixed after double-checking your situation, you can comment on the KDE bug.

As a workaround, you can use the attached small program - compile, chown to root, chmod +s and e.g. pin it to a key sequence (like `/path/to/bright +5 intel_backlight`).
[bright.c.gz](https://github.com/OpenMandrivaAssociation/distribution/files/9262210/bright.c.gz)

**Comment by benbullard79** [comment] 2022-08-11 00:24
[AngryPenguinPL](https://github.com/AngryPenguinPL) suggestion in 2nd post is a good one. This has worked for some users.

My understanding is no one in OM contributor group can reproduce this exact issue. In this case hardware matters as laptops vary in how the handle brightness settings.

If we can't reproduce the issue and the original poster (OP) does not respond we are stuck.

It has been suggested that getting rid of `acpi_osi=Linux acpi_osi='!Windows 2012' acpi_backlight=vendor` in the kernel command line would fix this. But we need someone with the issue to test this or other possible fixes.

That could be a tricky fix as _I think_ those were added to fix brightness controls not working on some other laptops.

Long term best solution would be for manufacturers to have more uniform setting for this. That will not happen in my lifetime.

**Comment by rugyada** [comment] 2022-08-29 16:03
No reply from OP. No way to know if suggested workaround works.
No way also to know whether a real bug or user/local misconfigurated whatsoever.

Possible solutions as described here:
https://forum.openmandriva.org/t/4605

Feel free to reopen when you have any useful feedback.
Feel free as well to provide a patch or submit a Pull Request

**Closed by rugyada** 2022-08-29 16:03 UTC
Labels: needinfo

**Comment by omakuta** [comment] 2022-10-11 06:01
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/not-working-backlight-screen-brightness-adjustement/4676/2
